# Generated by Django 5.2 on 2025-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_rename_watchlist_review_watchlist_review_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='number_of_rating',
            field=models.IntegerField(default=0),
        ),
    ]
